### ISSUE TITLE
Feature: 프로젝트 초기 세팅

### ISSUE THREAD

**Issue by lcomment** [wooda-ege/wooda-backend#2]
## Description

> api 개발에 앞선 초기 개발환경 세팅

## To-do

- [x] 프로젝트 생성
- [x] Spring Rest Docs 관련 Gradle 기본 설정
- [x] Jpa Audit 설정
- [x] s3 업로드 관련 기본 구현 및 테스트
